"""Dependency ports for the v0.6 execution plane.

Runtime services depend on these contracts, never on ``app.py`` or HTTP handler
classes.  Concrete adapters keep the existing externally visible behaviour.
"""
from __future__ import annotations

from typing import Any, Dict, Iterator, Optional, Protocol, Tuple


class CandidateQueryPort(Protocol):
    def iter_upstream_candidates(self, requested_model: str | None, group_id: str | None = None) -> Iterator[Any]: ...
    def iter_aggregate_candidates(self, aggregate: Any, **kwargs: Any) -> Iterator[Any]: ...
    def resolve_aggregate(self, requested_model: str | None, route: Any) -> Optional[Tuple[Any, str]]: ...


class HealthStatePort(Protocol):
    def refresh_expired_cooldowns(self) -> None: ...
    def mark_success(self, candidate: Any) -> None: ...
    def mark_unusable(self, candidate: Any, error: str) -> None: ...
    def set_cooldown(self, idx: int, error: str, cooldown_seconds: int, reason: str) -> None: ...
    def set_aggregate_member_cooldown(self, member_id: str, error: str, cooldown_seconds: int, reason: str) -> None: ...


class UpstreamRequestPort(Protocol):
    def request(self, method: str, url: str, headers: Dict[str, str], body: bytes, *, stream: bool, timeout: int) -> Any: ...
    def close(self) -> None: ...


class ConcurrencyPort(Protocol):
    def lock_for(self, candidate: Any, enabled: bool) -> Any: ...
    def active_count(self, candidate: Any) -> int: ...
    def mark_stream_active(self, candidate: Any, delta: int) -> None: ...


class RequestObservabilityPort(Protocol):
    def start_live_request(self, request_id: str, path: str, requested_model: str, *, stream: bool) -> None: ...
    def update_live_request(self, request_id: str, **patch: Any) -> None: ...
    def finish_live_request(self, request_id: str, status: str = "done") -> None: ...
    def add_log(self, path: str, model: str, status: str, detail: str = "", **kwargs: Any) -> None: ...
    def patch_stream_lifecycle(self, request_id: str, attempt: int, candidate_label: str, usage: tuple[int, int, int, int, int], usage_source: str, **kwargs: Any) -> bool: ...


class ProtocolAdapterPort(Protocol):
    def resolve_endpoint(self, base_url: str, path: str) -> str: ...
    def build_request(self, *, base_url: str, auth_key: str, incoming_headers: Dict[str, str], stream: bool, waf_compatible: bool, waf_accept_policy: str) -> Dict[str, str]: ...
    def fetch_models(self, base_url: str, auth_key: str) -> tuple[str, Dict[str, str], int, list[Dict[str, Any]]]: ...


class ExecutionDependencies(Protocol):
    """Explicit I1 bridge for frozen execution semantics.

    This intentionally names every owner-facing capability consumed by the
    legacy coordinator.  It is supplied by the composition root, not imported
    from the legacy facade; later slices can replace these groups with the
    narrower public ports above without changing request semantics.
    """

    store: Any
    _upstream_client: UpstreamRequestPort
    _upstream_candidate_type: Any
    _all_models_failed_error_type: type[Exception]
    _stream_idle_timeout_error_type: type[Exception]
    _route_context_type: type
    debug_capture: Any

    def _now(self) -> str: ...
    def _is_rate_limited(self, status_code: Optional[int], raw: str) -> bool: ...
    def _is_quota_exhausted(self, status_code: Optional[int], raw: str) -> bool: ...
    def _is_waf_blocked_error(self, status_code: Optional[int], raw: str) -> bool: ...
    def _is_request_level_error(self, status_code: Optional[int], raw: str) -> bool: ...
    def _is_auto_model(self, requested_model: str | None, group: Any) -> bool: ...
    def _mode_for(self, group: Any) -> str: ...
    def _group_for(self, model: Any) -> Any: ...
    def _auth_for(self, group: Any, model: Any) -> str: ...
    def _is_server_error(self, status_code: int) -> bool: ...
    def _auto_cooldown_seconds(self, group: Any) -> int: ...
    def _classify_candidate_error(self, status_code: Optional[int], raw: str, error_kind: str = "http") -> Dict[str, Any]: ...
    def _log_aggregate_member_skip(self, path: str, aggregate: Any, member: Any, reason: str, message: str, group: Any, model: Any, requested_label: str, request_id: str, resolved_as: str) -> None: ...
    def _route_group_id(self, route: Any) -> str | None: ...
    def _resolve_aggregate(self, requested_model: str | None, route: Any) -> Optional[Tuple[Any, str]]: ...
    def _iter_upstream_candidates(self, requested_model: str | None, group_id: str | None = None) -> Iterator[Any]: ...
    def _iter_aggregate_candidates(self, aggregate: Any, **kwargs: Any) -> Iterator[Any]: ...
    def _resolve_url(self, base_url: str, path: str) -> str: ...
    def _tools_order_enabled(self) -> bool: ...
    def _normalize_tools_order(self, payload: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]: ...
    def _body_for_upstream(self, payload: Dict[str, Any], raw_body: bytes | None, requested_model: str | None, target_model: str) -> Tuple[bytes, str]: ...
    def _headers_for(self, group: Any, auth_key: str, incoming_headers: Dict[str, str], *, stream: bool) -> Dict[str, str]: ...
    def _candidate_lock(self, candidate: Any, incoming_headers: Dict[str, str]) -> Any: ...
    def _acquire_upstream_lock(self, lock: Any) -> Tuple[bool, int]: ...
    def _release_lock(self, lock: Any) -> None: ...
    def _waf_lock_busy_detail(self, candidate: Any, body: bytes, lock_wait_ms: int) -> str: ...
    def _stream_idle_timeout_seconds(self, group: Any) -> int: ...
    def _readline_with_idle_timeout(self, response: Any, timeout_seconds: int) -> bytes: ...
    def _usage_from_response(self, data: bytes) -> Tuple[int, int, int, int, int]: ...
    def _usage_from_stream_chunk(self, chunk: bytes) -> Tuple[int, int, int, int, int]: ...
    def _mark_success(self, candidate: Any) -> None: ...
    def _mark_unusable(self, candidate: Any, error: str) -> None: ...
    def _mark_stream_timeout(self, candidate: Any, error: str) -> int: ...
    def _mark_stream_active(self, candidate: Any, delta: int) -> None: ...
    def _set_cooldown(self, idx: int, error: str, cooldown_seconds: int, reason: str) -> None: ...
    def _set_unusable(self, idx: int, error: str) -> None: ...
    def _set_aggregate_member_cooldown(self, member_id: str, error: str, cooldown_seconds: int, reason: str) -> None: ...
    def _mark_aggregate_member_success(self, member_id: str) -> None: ...
    def _aggregate_cooldown_seconds(self, aggregate: Any) -> int: ...
    def _aggregate_log_suffix(self, **kwargs: Any) -> str: ...
    def _waf_blocked_suffix(self, classification: Dict[str, Any], group: Any) -> str: ...
    def _waf_blocked_hint(self, fallback_chain: list[Dict[str, Any]]) -> str: ...
    def _short_error(self, error: str) -> str: ...
    def _debug_detail(self, *args: Any, **kwargs: Any) -> str: ...
    def _payload_fingerprint(self, *args: Any, **kwargs: Any) -> str: ...
    def add_log(self, *args: Any, **kwargs: Any) -> None: ...
    def patch_stream_lifecycle(self, *args: Any, **kwargs: Any) -> bool: ...
    def _live_request_start(self, request_id: str, path: str, requested_model: str, *, stream: bool) -> None: ...
    def _live_request_update(self, request_id: str, **patch: Any) -> None: ...
    def _live_request_finish(self, request_id: str, status: str = "done") -> None: ...
